/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 23:40:38 GMT 2024
 */

package org.bouncycastle.crypto.params;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.math.BigInteger;
import org.bouncycastle.crypto.params.ElGamalKeyParameters;
import org.bouncycastle.crypto.params.ElGamalParameters;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ElGamalKeyParameters_ESTest extends ElGamalKeyParameters_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      BigInteger bigInteger0 = BigInteger.ZERO;
      ElGamalParameters elGamalParameters0 = new ElGamalParameters(bigInteger0, bigInteger0);
      BigInteger bigInteger1 = bigInteger0.flipBit(1);
      ElGamalKeyParameters elGamalKeyParameters0 = new ElGamalKeyParameters(false, elGamalParameters0);
      ElGamalParameters elGamalParameters1 = new ElGamalParameters(bigInteger1, bigInteger1);
      ElGamalKeyParameters elGamalKeyParameters1 = new ElGamalKeyParameters(true, elGamalParameters1);
      boolean boolean0 = elGamalKeyParameters0.equals(elGamalKeyParameters1);
      assertTrue(boolean0);
  }
}
