/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 02:06:20 GMT 2024
 */

package com.liferay.portlet.documentlibrary.util.comparator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.repository.model.FileEntry;
import com.liferay.portal.kernel.repository.model.Folder;
import com.liferay.portal.repository.proxy.FileEntryProxyBean;
import com.liferay.portal.repository.proxy.FolderProxyBean;
import com.liferay.portlet.documentlibrary.model.DLFileShortcut;
import com.liferay.portlet.documentlibrary.util.comparator.RepositoryModelCreateDateComparator;
import java.time.Instant;
import java.util.Date;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RepositoryModelCreateDateComparator_ESTest extends RepositoryModelCreateDateComparator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Instant instant0 = MockInstant.ofEpochSecond(0L);
      Date date0 = Date.from(instant0);
      FileEntry fileEntry0 = mock(FileEntry.class, new ViolatedAssumptionAnswer());
      doReturn((Date) null, date0).when(fileEntry0).getCreateDate();
      RepositoryModelCreateDateComparator repositoryModelCreateDateComparator0 = new RepositoryModelCreateDateComparator(true);
      int int0 = repositoryModelCreateDateComparator0.compare(fileEntry0, fileEntry0);
      assertEquals(1, int0);
  }
}
