/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 03:25:23 GMT 2024
 */

package de.huxhorn.lilith.consumers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import de.huxhorn.lilith.consumers.AlarmSoundLoggingEventConsumer;
import de.huxhorn.lilith.data.eventsource.EventIdentifier;
import de.huxhorn.lilith.data.eventsource.EventWrapper;
import de.huxhorn.lilith.data.eventsource.SourceIdentifier;
import de.huxhorn.lilith.data.logging.LoggingEvent;
import de.huxhorn.sulky.sounds.Sounds;
import de.huxhorn.sulky.sounds.jlayer.JLayerSounds;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AlarmSoundLoggingEventConsumer_ESTest extends AlarmSoundLoggingEventConsumer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AlarmSoundLoggingEventConsumer alarmSoundLoggingEventConsumer0 = new AlarmSoundLoggingEventConsumer();
      JLayerSounds jLayerSounds0 = new JLayerSounds();
      jLayerSounds0.setMute(true);
      alarmSoundLoggingEventConsumer0.setSounds(jLayerSounds0);
      Sounds sounds0 = alarmSoundLoggingEventConsumer0.getSounds();
      assertSame(sounds0, jLayerSounds0);
  }
}
