/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 00:43:29 GMT 2024
 */

package com.atlassw.tools.eclipse.checkstyle.config;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.atlassw.tools.eclipse.checkstyle.config.ConfigProperty;
import com.atlassw.tools.eclipse.checkstyle.config.Module;
import com.atlassw.tools.eclipse.checkstyle.config.meta.RuleGroupMetadata;
import com.atlassw.tools.eclipse.checkstyle.config.meta.RuleMetadata;
import com.puppycrawl.tools.checkstyle.api.SeverityLevel;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Module_ESTest extends Module_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SeverityLevel severityLevel0 = SeverityLevel.WARNING;
      SeverityLevel severityLevel1 = SeverityLevel.INFO;
      RuleGroupMetadata ruleGroupMetadata0 = mock(RuleGroupMetadata.class, new ViolatedAssumptionAnswer());
      RuleMetadata ruleMetadata0 = new RuleMetadata("com.atlassw.tools.eclipse.checkstyle.config.Module", "", "", severityLevel1, true, true, true, true, ruleGroupMetadata0);
      Module module0 = new Module(ruleMetadata0, true);
      module0.setSeverity(severityLevel0);
      SeverityLevel severityLevel2 = SeverityLevel.IGNORE;
      module0.setSeverity(severityLevel2);
      assertNull(module0.getId());
  }
}
