/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 04:26:13 GMT 2024
 */

package com.lts.swing.contentpanel;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.lts.swing.TextContentPanel;
import com.lts.swing.contentpanel.CPMouseListener;
import com.lts.swing.contentpanel.SimpleMouseListener;
import java.awt.Component;
import java.awt.IllegalComponentStateException;
import java.awt.event.MouseEvent;
import java.awt.event.MouseWheelEvent;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JViewport;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CPMouseListener_ESTest extends CPMouseListener_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TextContentPanel textContentPanel0 = new TextContentPanel("zY)^F", (-2106), "zY)^F");
      JScrollPane jScrollPane0 = new JScrollPane(textContentPanel0);
      JViewport jViewport0 = jScrollPane0.getViewport();
      JPopupMenu jPopupMenu0 = new JPopupMenu("f-G");
      textContentPanel0.registerPopup(jViewport0, jPopupMenu0);
      CPMouseListener cPMouseListener0 = textContentPanel0.getMouseListener();
      // Undeclared exception!
      try { 
        cPMouseListener0.showPopup(jViewport0, 1, 3);
        fail("Expecting exception: IllegalComponentStateException");
      
      } catch(IllegalComponentStateException e) {
         //
         // component must be showing on the screen to determine its location
         //
         verifyException("java.awt.Component", e);
      }
  }
}
