/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 23:07:04 GMT 2024
 */

package com.eteks.sweethome3d.viewcontroller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.eteks.sweethome3d.model.AspectRatio;
import com.eteks.sweethome3d.model.Camera;
import com.eteks.sweethome3d.model.Home;
import com.eteks.sweethome3d.model.ObserverCamera;
import com.eteks.sweethome3d.model.UserPreferences;
import com.eteks.sweethome3d.swing.SwingViewFactory;
import com.eteks.sweethome3d.viewcontroller.ContentManager;
import com.eteks.sweethome3d.viewcontroller.PhotoController;
import com.eteks.sweethome3d.viewcontroller.ThreadedTaskController;
import com.eteks.sweethome3d.viewcontroller.ThreadedTaskView;
import com.eteks.sweethome3d.viewcontroller.View;
import java.util.concurrent.Callable;
import javax.swing.plaf.synth.SynthOptionPaneUI;
import javax.swing.plaf.synth.SynthToolBarUI;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PhotoController_ESTest extends PhotoController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Home home0 = new Home();
      SwingViewFactory swingViewFactory0 = new SwingViewFactory();
      Callable<Void> callable0 = (Callable<Void>) mock(Callable.class, new ViolatedAssumptionAnswer());
      ThreadedTaskController.ExceptionHandler threadedTaskController_ExceptionHandler0 = mock(ThreadedTaskController.ExceptionHandler.class, new ViolatedAssumptionAnswer());
      ThreadedTaskController threadedTaskController0 = new ThreadedTaskController(callable0, "LENS", threadedTaskController_ExceptionHandler0, (UserPreferences) null, swingViewFactory0);
      ThreadedTaskView threadedTaskView0 = threadedTaskController0.getView();
      PhotoController photoController0 = new PhotoController(home0, (UserPreferences) null, threadedTaskView0, swingViewFactory0, (ContentManager) null);
      photoController0.get3DView();
      assertEquals(1.0F, photoController0.get3DViewAspectRatio(), 0.01F);
      assertEquals(1392409281320L, photoController0.getTime());
      assertEquals(13684944, photoController0.getCeilingLightColor());
      assertEquals(300, photoController0.getHeight());
      assertEquals(400, photoController0.getWidth());
  }
}
