/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 05:05:50 GMT 2024
 */

package org.sourceforge.ifx.basetypes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.sourceforge.ifx.basetypes.IFXHexBinary;
import org.sourceforge.ifx.basetypes.IFXLong;
import org.sourceforge.ifx.basetypes.IFXObject;
import org.sourceforge.ifx.basetypes.IFXString;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IFXObject_ESTest extends IFXObject_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IFXObject iFXObject0 = new IFXObject();
      IFXObject iFXObject1 = new IFXObject();
      boolean boolean0 = iFXObject1.equals(iFXObject0);
      assertTrue(boolean0);
  }
}
