/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 22:41:34 GMT 2024
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.DirEntry;
import javax.xml.namespace.QName;
import org.apache.axis.description.TypeDesc;
import org.apache.axis.encoding.Deserializer;
import org.apache.axis.encoding.Serializer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DirEntry_ESTest extends DirEntry_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      QName qName0 = new QName("9Rx6rNHc$::j");
      Class<DirEntry> class0 = DirEntry.class;
      Serializer serializer0 = DirEntry.getSerializer("9Rx6rNHc$::j", class0, qName0);
      assertEquals("Axis SAX Mechanism", serializer0.getMechanismType());
  }
}
