/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 22:48:48 GMT 2024
 */

package net.sourceforge.squirrel_sql.client.gui.db;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.GraphicsConfiguration;
import java.awt.HeadlessException;
import net.sourceforge.squirrel_sql.client.IApplication;
import net.sourceforge.squirrel_sql.client.gui.db.DriverInternalFrame;
import net.sourceforge.squirrel_sql.client.gui.desktopcontainer.DesktopStyle;
import net.sourceforge.squirrel_sql.client.gui.mainframe.MainFrame;
import net.sourceforge.squirrel_sql.fw.id.IntegerIdentifier;
import net.sourceforge.squirrel_sql.fw.sql.ISQLDriver;
import net.sourceforge.squirrel_sql.fw.sql.SQLDriver;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DriverInternalFrame_ESTest extends DriverInternalFrame_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DesktopStyle desktopStyle0 = mock(DesktopStyle.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(desktopStyle0).isDockTabStyle();
      MainFrame mainFrame0 = mock(MainFrame.class, new ViolatedAssumptionAnswer());
      IApplication iApplication0 = mock(IApplication.class, new ViolatedAssumptionAnswer());
      doReturn(desktopStyle0).when(iApplication0).getDesktopStyle();
      doReturn(mainFrame0).when(iApplication0).getMainFrame();
      SQLDriver sQLDriver0 = new SQLDriver();
      String[] stringArray0 = new String[2];
      stringArray0[0] = "net.sourceforge.squirrel_sql.client.gui.db.DriverInternalFrame$6";
      stringArray0[1] = "net.sourceforge.squirrel_sql.client.gui.db.DriverInternalFrame$6";
      sQLDriver0.setJarFileNames(stringArray0);
      DriverInternalFrame driverInternalFrame0 = new DriverInternalFrame(iApplication0, sQLDriver0, 3);
      assertEquals(549, driverInternalFrame0.getWidth());
      assertEquals(467, driverInternalFrame0.getHeight());
  }
}
