/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 04:00:43 GMT 2024
 */

package org.exolab.jms.tools.admin;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Component;
import java.beans.PropertyChangeListener;
import java.util.Hashtable;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.JTree;
import javax.swing.plaf.synth.SynthSpinnerUI;
import javax.swing.plaf.synth.SynthTabbedPaneUI;
import javax.swing.tree.TreeNode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.exolab.jms.tools.admin.AdminInfo;
import org.exolab.jms.tools.admin.OpenJMSConsumer;
import org.exolab.jms.tools.admin.OpenJMSQueue;
import org.exolab.jms.tools.admin.OpenJMSTopic;
import org.exolab.jms.tools.admin.OpenJMSTopicFolder;
import org.exolab.jms.tools.admin.OpenJMSUser;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AdminInfo_ESTest extends AdminInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AdminInfo adminInfo0 = new AdminInfo();
      Hashtable<SynthTabbedPaneUI, SynthTabbedPaneUI> hashtable0 = new Hashtable<SynthTabbedPaneUI, SynthTabbedPaneUI>(1);
      JTree jTree0 = new JTree(hashtable0);
      Component component0 = adminInfo0.getTreeCellRendererComponent(jTree0, jTree0, true, false, true, 0, false);
      assertTrue(component0.getFocusTraversalKeysEnabled());
  }
}
