/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 00:47:41 GMT 2024
 */

package weka.associations;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Array;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import weka.associations.ItemSet;
import weka.core.Attribute;
import weka.core.BinarySparseInstance;
import weka.core.DenseInstance;
import weka.core.FastVector;
import weka.core.Instance;
import weka.core.Instances;
import weka.core.SparseInstance;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ItemSet_ESTest extends ItemSet_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ItemSet itemSet0 = new ItemSet(0);
      int[] intArray0 = new int[5];
      ItemSet itemSet1 = new ItemSet(0, intArray0);
      int[] intArray1 = new int[5];
      intArray1[0] = 1804;
      itemSet0.setItem(intArray1);
      boolean boolean0 = itemSet0.equals(itemSet1);
      assertFalse(boolean0);
      assertFalse(itemSet1.getTreatZeroAsMissing());
      assertFalse(itemSet0.getTreatZeroAsMissing());
      assertFalse(itemSet1.equals((Object)itemSet0));
      assertEquals(1, itemSet1.support());
  }
}
