/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 02:48:07 GMT 2024
 */

package com.rakegroup;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.rakegroup.JoomlaOutput;
import java.io.File;
import java.util.Vector;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.Project;
import org.apache.tools.ant.types.FileSet;
import org.apache.tools.ant.types.TarFileSet;
import org.apache.tools.ant.types.ZipFileSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jdom.Content;
import org.jdom.Element;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JoomlaOutput_ESTest extends JoomlaOutput_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Project project0 = new Project();
      File file0 = project0.resolveFile("");
      FileSet fileSet0 = new FileSet();
      fileSet0.setDir(file0);
      JoomlaOutput.Files joomlaOutput_Files0 = new JoomlaOutput.Files();
      joomlaOutput_Files0.addConfiguredFileSet(fileSet0);
      JoomlaOutput.Option joomlaOutput_Option0 = new JoomlaOutput.Option();
      Element element0 = joomlaOutput_Option0.setContent((Content) joomlaOutput_Files0);
      JoomlaOutput.SimpleElement.fixup(project0, joomlaOutput_Option0);
      assertSame(joomlaOutput_Option0, element0);
  }
}
