/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 05:10:52 GMT 2024
 */

package de.progra.charting.render;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import de.progra.charting.CoordSystem;
import de.progra.charting.model.ChartDataModel;
import de.progra.charting.model.ObjectChartDataModel;
import de.progra.charting.render.PieChartRenderer;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PieChartRenderer_ESTest extends PieChartRenderer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ObjectChartDataModel objectChartDataModel0 = new ObjectChartDataModel();
      PieChartRenderer pieChartRenderer0 = new PieChartRenderer(objectChartDataModel0);
      Integer integer0 = new Integer(2147473695);
      Graphics2D graphics2D0 = mock(Graphics2D.class, new ViolatedAssumptionAnswer());
      doReturn(integer0).when(graphics2D0).getRenderingHint(any(java.awt.RenderingHints.Key.class));
      Dimension dimension0 = pieChartRenderer0.getPreferredSize();
      Rectangle rectangle0 = new Rectangle(dimension0);
      rectangle0.setSize(2147473674, 2147473695);
      pieChartRenderer0.bounds = rectangle0;
      // Undeclared exception!
      pieChartRenderer0.renderChart(graphics2D0);
  }
}
