/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 22:59:24 GMT 2024
 */

package net.sourceforge.squirrel_sql.client.session.parser.kernel;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import net.sourceforge.squirrel_sql.client.session.parser.kernel.ErrorStream;
import net.sourceforge.squirrel_sql.client.session.parser.kernel.Parser;
import net.sourceforge.squirrel_sql.client.session.parser.kernel.ParserListener;
import net.sourceforge.squirrel_sql.client.session.parser.kernel.SQLCompletion;
import net.sourceforge.squirrel_sql.client.session.parser.kernel.SQLSchema;
import net.sourceforge.squirrel_sql.client.session.parser.kernel.Scanner;
import net.sourceforge.squirrel_sql.client.session.parser.kernel.completions.SQLModifyingStatement;
import net.sourceforge.squirrel_sql.client.session.parser.kernel.completions.SQLSelectStatement;
import net.sourceforge.squirrel_sql.client.session.parser.kernel.completions.SQLSelectStatementListener;
import net.sourceforge.squirrel_sql.client.session.parser.kernel.completions.SQLStatement;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Parser_ESTest extends Parser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      File file0 = MockFile.createTempFile(";ouEVgQU%/V{vjyj", ";ouEVgQU%/V{vjyj");
      Scanner.FBuffer scanner_FBuffer0 = new Scanner.FBuffer(file0);
      ErrorStream errorStream0 = new ErrorStream();
      Scanner scanner0 = new Scanner(scanner_FBuffer0, errorStream0);
      SQLSelectStatement sQLSelectStatement0 = new SQLSelectStatement(78);
      Parser parser0 = new Parser(scanner0, sQLSelectStatement0);
      parser0.parse();
      String string0 = parser0.LexName();
      assertEquals("\uFFFF", string0);
  }
}
