/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 03:38:53 GMT 2024
 */

package dk.statsbiblioteket.summa.common.rpc;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dk.statsbiblioteket.summa.common.configuration.Configuration;
import dk.statsbiblioteket.summa.common.rpc.ConnectionConsumer;
import java.io.InputStream;
import java.io.Serializable;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ConnectionConsumer_ESTest extends ConnectionConsumer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Serializable[] serializableArray0 = new Serializable[0];
      Configuration configuration0 = Configuration.newMemoryBased(serializableArray0);
      ConnectionConsumer<Object> connectionConsumer0 = new ConnectionConsumer<Object>(configuration0, "");
      String string0 = connectionConsumer0.getVendorId();
      assertEquals("", string0);
  }
}
