/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 23:53:14 GMT 2024
 */

package org.gudy.azureus2.ui.console.commands;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.aelitis.azureus.core.AzureusCore;
import com.aelitis.azureus.plugins.dht.DHTPlugin;
import com.aelitis.azureus.ui.common.table.TableColumnCore;
import java.io.PrintStream;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.gudy.azureus2.core3.download.DownloadManager;
import org.gudy.azureus2.ui.console.ConsoleInput;
import org.gudy.azureus2.ui.console.commands.Show;
import org.gudy.azureus2.ui.swt.views.table.painted.TableViewPainted;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Show_ESTest extends Show_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Show show0 = new Show();
      Class<Long> class0 = Long.class;
      TableViewPainted tableViewPainted0 = new TableViewPainted(class0, "Total Connected Peers (seeds/peers): ", "g\"6e@vjcA'\"^f\"'", (TableColumnCore[]) null, "Status: ", (-7));
      List<Object> list0 = tableViewPainted0.getSelectedDataSources();
      // Undeclared exception!
      try { 
        show0.execute("g\"6e@vjcA'\"^f\"'", (ConsoleInput) null, list0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.ui.console.commands.Show", e);
      }
  }
}
