/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 05:17:35 GMT 2024
 */

package org.jcvi.jillion.core.residue.nt;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.BufferUnderflowException;
import java.util.Collection;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.Stack;
import java.util.function.UnaryOperator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jcvi.jillion.core.Range;
import org.jcvi.jillion.core.residue.nt.ACGTNNucloetideCodec;
import org.jcvi.jillion.core.residue.nt.DefaultNucleotideCodec;
import org.jcvi.jillion.core.residue.nt.DefaultNucleotideSequence;
import org.jcvi.jillion.core.residue.nt.NoAmbiguitiesEncodedNucleotideCodec;
import org.jcvi.jillion.core.residue.nt.Nucleotide;
import org.jcvi.jillion.core.residue.nt.NucleotideCodec;
import org.jcvi.jillion.core.residue.nt.NucleotideSequence;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultNucleotideSequence_ESTest extends DefaultNucleotideSequence_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DefaultNucleotideCodec defaultNucleotideCodec0 = DefaultNucleotideCodec.INSTANCE;
      byte[] byteArray0 = new byte[9];
      DefaultNucleotideSequence defaultNucleotideSequence0 = new DefaultNucleotideSequence(defaultNucleotideCodec0, byteArray0);
      byte[] byteArray1 = new byte[4];
      byteArray1[0] = (byte)14;
      DefaultNucleotideSequence defaultNucleotideSequence1 = new DefaultNucleotideSequence(defaultNucleotideCodec0, byteArray1);
      boolean boolean0 = defaultNucleotideSequence0.equals(defaultNucleotideSequence1);
      assertFalse(boolean0);
  }
}
