/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 22:52:04 GMT 2024
 */

package net.sourceforge.squirrel_sql.client.mainframe.action;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import net.sourceforge.squirrel_sql.client.IApplication;
import net.sourceforge.squirrel_sql.client.gui.db.IToogleableAliasesList;
import net.sourceforge.squirrel_sql.client.mainframe.action.ToggleTreeViewAction;
import net.sourceforge.squirrel_sql.client.resources.SquirrelResources;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ToggleTreeViewAction_ESTest extends ToggleTreeViewAction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IApplication iApplication0 = mock(IApplication.class, new ViolatedAssumptionAnswer());
      doReturn((SquirrelResources) null).when(iApplication0).getResources();
      ToggleTreeViewAction toggleTreeViewAction0 = null;
      try {
        toggleTreeViewAction0 = new ToggleTreeViewAction(iApplication0, (IToogleableAliasesList) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No Resources object in IApplication
         //
         verifyException("net.sourceforge.squirrel_sql.client.action.SquirrelAction", e);
      }
  }
}
