/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 00:09:36 GMT 2024
 */

package org.gudy.azureus2.ui.console.commands;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.aelitis.azureus.core.AzureusCore;
import java.io.StringReader;
import java.util.List;
import java.util.ResourceBundle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.gudy.azureus2.ui.console.ConsoleInput;
import org.gudy.azureus2.ui.console.commands.XML;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class XML_ESTest extends XML_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      XML xML0 = new XML();
      StringReader stringReader0 = new StringReader("0Uv9lx2mLhX]AO");
      MockPrintStream mockPrintStream0 = new MockPrintStream("0Uv9lx2mLhX]AO");
      Boolean boolean0 = Boolean.valueOf("");
      ConsoleInput consoleInput0 = new ConsoleInput("", (AzureusCore) null, stringReader0, mockPrintStream0, boolean0);
      List<String> list0 = ResourceBundle.Control.FORMAT_PROPERTIES;
      xML0.execute("Ignoring peer's LT extension protocol support, as disabled for this download.", consoleInput0, list0);
      assertNull(xML0.getShortCommandName());
  }
}
