/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 04:29:47 GMT 2024
 */

package com.lts.swing.table;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.lts.swing.table.JTableUtils;
import java.awt.Rectangle;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import java.util.List;
import java.util.Stack;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.text.DefaultEditorKit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JTableUtils_ESTest extends JTableUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Rectangle rectangle0 = new Rectangle();
      Object[][] objectArray0 = new Object[4][9];
      Object[] objectArray1 = new Object[1];
      objectArray1[0] = (Object) rectangle0;
      objectArray0[0] = objectArray1;
      JTable jTable0 = new JTable(objectArray0, objectArray0[0]);
      String[] stringArray0 = new String[3];
      JComboBox jComboBox0 = JTableUtils.setupComboBox(0, jTable0, stringArray0);
      assertFalse(jComboBox0.getIgnoreRepaint());
  }
}
