/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 03:42:25 GMT 2024
 */

package ch.bfh.egov.nutzenportfolio.action;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ch.bfh.egov.nutzenportfolio.action.DetailzieleAction;
import ch.bfh.egov.nutzenportfolio.form.FragenForm;
import ch.bfh.egov.nutzenportfolio.form.NaOpNuForm;
import ch.bfh.egov.nutzenportfolio.form.ProjektattraktivitaetForm;
import ch.bfh.egov.nutzenportfolio.persistence.common.CommonDao;
import ch.bfh.egov.nutzenportfolio.persistence.common.CommonIbatisDao;
import ch.bfh.egov.nutzenportfolio.persistence.customizing.CustomizingDao;
import ch.bfh.egov.nutzenportfolio.persistence.customizing.CustomizingIbatisDao;
import ch.bfh.egov.nutzenportfolio.persistence.detailziele.DetailzieleIbatisDao;
import ch.bfh.egov.nutzenportfolio.persistence.strategischeziele.StrategischeZieleIbatisDao;
import ch.bfh.egov.nutzenportfolio.service.common.CommonDaoService;
import ch.bfh.egov.nutzenportfolio.service.common.CommonService;
import ch.bfh.egov.nutzenportfolio.service.customizing.CustomizingDaoService;
import ch.bfh.egov.nutzenportfolio.service.customizing.CustomizingService;
import ch.bfh.egov.nutzenportfolio.service.detailziele.DetailzieleDaoService;
import ch.bfh.egov.nutzenportfolio.service.detailziele.DetailzieleService;
import ch.bfh.egov.nutzenportfolio.service.strategischeziele.StrategischeZieleDaoService;
import ch.bfh.egov.nutzenportfolio.service.strategischeziele.StrategischeZieleService;
import javax.servlet.ServletRequestWrapper;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletRequestWrapper;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpServletResponseWrapper;
import javax.servlet.http.HttpSession;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.upload.CommonsMultipartRequestHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DetailzieleAction_ESTest extends DetailzieleAction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ActionMapping actionMapping0 = new ActionMapping();
      DetailzieleIbatisDao detailzieleIbatisDao0 = new DetailzieleIbatisDao();
      DetailzieleDaoService detailzieleDaoService0 = new DetailzieleDaoService(detailzieleIbatisDao0);
      DetailzieleAction detailzieleAction0 = new DetailzieleAction(detailzieleDaoService0, (StrategischeZieleService) null, (CommonService) null, (CustomizingService) null);
      FragenForm fragenForm0 = new FragenForm();
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      HttpServletRequestWrapper httpServletRequestWrapper0 = new HttpServletRequestWrapper(httpServletRequest0);
      httpServletRequestWrapper0.setRequest(httpServletRequestWrapper0);
      // Undeclared exception!
      try { 
        detailzieleAction0.list(actionMapping0, fragenForm0, httpServletRequestWrapper0, (HttpServletResponse) null);
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
