/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 03:31:56 GMT 2024
 */

package de.huxhorn.lilith.engine;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import de.huxhorn.lilith.data.access.AccessEvent;
import de.huxhorn.lilith.data.eventsource.EventWrapper;
import de.huxhorn.lilith.engine.AccessFileBufferFactory;
import de.huxhorn.lilith.engine.LogFileFactory;
import de.huxhorn.sulky.codec.Codec;
import de.huxhorn.sulky.codec.filebuffer.MetaData;
import java.util.HashMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AccessFileBufferFactory_ESTest extends AccessFileBufferFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      hashMap0.put("contentFormat", "protobuf");
      MetaData metaData0 = new MetaData(hashMap0);
      AccessFileBufferFactory accessFileBufferFactory0 = new AccessFileBufferFactory((LogFileFactory) null, hashMap0);
      Codec<EventWrapper<AccessEvent>> codec0 = accessFileBufferFactory0.resolveCodec(metaData0);
      assertNotNull(codec0);
  }
}
