/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 04:07:30 GMT 2024
 */

package bible.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import bible.util.DbConnectionAttributes;
import bible.util.DbConnectionBroker;
import java.sql.SQLException;
import java.util.Vector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DbConnectionBroker_ESTest extends DbConnectionBroker_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DbConnectionBroker dbConnectionBroker0 = new DbConnectionBroker();
      Vector vector0 = dbConnectionBroker0.getOpenConnections();
      assertEquals(0, dbConnectionBroker0.getMaxReached());
      assertEquals(0, vector0.size());
  }
}
