/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 04:18:00 GMT 2024
 */

package com.hf.sfm.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.hf.sfm.util.DaoFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DaoFactory_ESTest extends DaoFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DaoFactory daoFactory0 = new DaoFactory();
      Object object0 = new Object();
      String string0 = daoFactory0.encrypt("");
      String string1 = daoFactory0.encrypt(string0);
      assertEquals("", string1);
  }
}
