/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 02:29:18 GMT 2024
 */

package com.liferay.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.util.PwdGenerator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PwdGenerator_ESTest extends PwdGenerator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = PwdGenerator.getPassword(2434);
      PwdGenerator.getPassword(string0, 2434, true);
      String string1 = PwdGenerator.getPassword(2434);
      PwdGenerator.getSecurePassword(string0, 2434, false);
      // Undeclared exception!
      PwdGenerator.getSecurePassword(string1, 2434);
  }
}
