/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 23:45:30 GMT 2024
 */

package org.gudy.azureus2.core3.disk.impl.resume;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.gudy.azureus2.core3.disk.DiskManagerFileInfo;
import org.gudy.azureus2.core3.disk.impl.DiskManagerHelper;
import org.gudy.azureus2.core3.disk.impl.DiskManagerImpl;
import org.gudy.azureus2.core3.disk.impl.access.impl.DMCheckerImpl;
import org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler;
import org.gudy.azureus2.core3.download.DownloadManager;
import org.gudy.azureus2.core3.download.DownloadManagerState;
import org.gudy.azureus2.core3.download.impl.DownloadManagerStateImpl;
import org.gudy.azureus2.core3.torrent.TOTorrent;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RDResumeHandler_ESTest extends RDResumeHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DownloadManagerState downloadManagerState0 = DownloadManagerStateImpl.getDownloadState((DownloadManager) null);
      HashMap<Integer, Integer> hashMap0 = new HashMap<Integer, Integer>();
      boolean boolean0 = RDResumeHandler.isTorrentResumeDataComplete(downloadManagerState0, (Map) hashMap0);
      assertFalse(boolean0);
  }
}
