/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 01:47:55 GMT 2024
 */

package com.liferay.portal.spring.context;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.spring.context.ArrayApplicationContext;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.support.SimpleBeanDefinitionRegistry;
import org.springframework.beans.factory.xml.XmlBeanDefinitionReader;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ArrayApplicationContext_ESTest extends ArrayApplicationContext_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[0];
      SimpleBeanDefinitionRegistry simpleBeanDefinitionRegistry0 = new SimpleBeanDefinitionRegistry();
      XmlBeanDefinitionReader xmlBeanDefinitionReader0 = new XmlBeanDefinitionReader(simpleBeanDefinitionRegistry0);
      ArrayApplicationContext arrayApplicationContext0 = new ArrayApplicationContext(stringArray0);
      arrayApplicationContext0.setConfigLocation("applicationEventMulticaster");
      arrayApplicationContext0.loadBeanDefinitions(xmlBeanDefinitionReader0);
      assertEquals(2, XmlBeanDefinitionReader.VALIDATION_DTD);
  }
}
