/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 05:24:02 GMT 2024
 */

package org.quickserver.util.xmlreader;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.Socket;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockSocket;
import org.junit.runner.RunWith;
import org.quickserver.util.xmlreader.AccessConstraintConfig;
import org.quickserver.util.xmlreader.IpFilterConfig;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AccessConstraintConfig_ESTest extends AccessConstraintConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AccessConstraintConfig accessConstraintConfig0 = new AccessConstraintConfig();
      IpFilterConfig ipFilterConfig0 = new IpFilterConfig();
      accessConstraintConfig0.setIpFilterConfig(ipFilterConfig0);
      ipFilterConfig0.setEnable(true);
      IpFilterConfig ipFilterConfig1 = accessConstraintConfig0.getIpFilterConfig();
      assertSame(ipFilterConfig1, ipFilterConfig0);
  }
}
