/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 03:15:01 GMT 2024
 */

package net.sourceforge.jwbf.inyoka.actions;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import net.sourceforge.jwbf.core.actions.FilePost;
import net.sourceforge.jwbf.core.actions.util.HttpAction;
import net.sourceforge.jwbf.core.contentRep.SimpleArticle;
import net.sourceforge.jwbf.inyoka.actions.GetRevision;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GetRevision_ESTest extends GetRevision_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GetRevision getRevision0 = new GetRevision("net.sourceforge.jwbf.core.actions.util.ProcessException");
      HttpAction httpAction0 = getRevision0.getNextMessage();
      assertEquals("/net.sourceforge.jwbf.core.actions.util.ProcessException?action=export&format=raw&", httpAction0.getRequest());
      
      HttpAction httpAction1 = getRevision0.getNextMessage();
      assertEquals("/net.sourceforge.jwbf.core.actions.util.ProcessException", httpAction1.getRequest());
      
      boolean boolean0 = getRevision0.hasMoreMessages();
      assertTrue(boolean0);
  }
}
