/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 00:29:06 GMT 2024
 */

package org.gudy.azureus2.ui.swt.views.tableitems.tracker;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.gudy.azureus2.plugins.ui.tables.TableCell;
import org.gudy.azureus2.plugins.ui.tables.TableColumn;
import org.gudy.azureus2.plugins.ui.tables.TableColumnInfo;
import org.gudy.azureus2.ui.swt.views.table.TableRowSWT;
import org.gudy.azureus2.ui.swt.views.table.impl.FakeTableCell;
import org.gudy.azureus2.ui.swt.views.table.painted.TableCellPainted;
import org.gudy.azureus2.ui.swt.views.table.utils.TableColumnInfoImpl;
import org.gudy.azureus2.ui.swt.views.tableitems.tracker.PeersItem;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PeersItem_ESTest extends PeersItem_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PeersItem peersItem0 = new PeersItem();
      TableCellPainted tableCellPainted0 = new TableCellPainted((TableRowSWT) null, peersItem0, (-373));
      boolean boolean0 = tableCellPainted0.refresh(false, false);
      assertFalse(boolean0);
      
      peersItem0.refresh(tableCellPainted0);
      assertEquals((-1), peersItem0.getRefreshInterval());
  }
}
