/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 03:11:43 GMT 2024
 */

package com.yahoo.platform.yui.compressor;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.yahoo.platform.yui.compressor.JavaScriptIdentifier;
import com.yahoo.platform.yui.compressor.ScriptOrFnScope;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ScriptOrFnScope_ESTest extends ScriptOrFnScope_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope((-870), (ScriptOrFnScope) null);
      JavaScriptIdentifier javaScriptIdentifier0 = scriptOrFnScope0.declareIdentifier("P3XkInd+");
      JavaScriptIdentifier javaScriptIdentifier1 = scriptOrFnScope0.getIdentifier("P3XkInd+");
      assertSame(javaScriptIdentifier1, javaScriptIdentifier0);
  }
}
