/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 03:28:45 GMT 2024
 */

package de.huxhorn.lilith.data.logging.protobuf;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.protobuf.ExtensionRegistry;
import de.huxhorn.lilith.data.eventsource.EventIdentifier;
import de.huxhorn.lilith.data.eventsource.EventWrapper;
import de.huxhorn.lilith.data.eventsource.SourceIdentifier;
import de.huxhorn.lilith.data.logging.LoggingEvent;
import de.huxhorn.lilith.data.logging.protobuf.LoggingEventWrapperProtobufDecoder;
import de.huxhorn.lilith.data.logging.protobuf.generated.LoggingProto;
import java.io.InputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LoggingEventWrapperProtobufDecoder_ESTest extends LoggingEventWrapperProtobufDecoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      LoggingProto.SourceIdentifier loggingProto_SourceIdentifier0 = LoggingProto.SourceIdentifier.parseFrom(byteArray0);
      SourceIdentifier sourceIdentifier0 = LoggingEventWrapperProtobufDecoder.convert(loggingProto_SourceIdentifier0);
      assertNull(sourceIdentifier0.getIdentifier());
  }
}
