/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 22:45:11 GMT 2024
 */

package net.sourceforge.squirrel_sql.client.gui;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.URL;
import java.net.URLStreamHandler;
import net.sourceforge.squirrel_sql.client.gui.HtmlViewerPanel;
import net.sourceforge.squirrel_sql.client.gui.IHtmlViewerPanelListener;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.jboss.net.protocol.resource.Handler;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HtmlViewerPanel_ESTest extends HtmlViewerPanel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      URL uRL0 = MockURL.getFtpExample();
      URL uRL1 = MockURL.getHttpExample();
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel(uRL0);
      htmlViewerPanel0.gotoURL(uRL1);
      URL uRL2 = MockURL.getFtpExample();
      htmlViewerPanel0.gotoURL(uRL2);
      htmlViewerPanel0.goBack();
      htmlViewerPanel0.goForward();
      assertFalse(htmlViewerPanel0.isFocusTraversalPolicyProvider());
  }
}
