/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 03:49:09 GMT 2024
 */

package visu.handball.moves.views;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.lowagie.text.Graphic;
import com.lowagie.text.pdf.AsianFontMapper;
import com.lowagie.text.pdf.FontMapper;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import javax.swing.DebugGraphics;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import visu.handball.moves.model.ColorModel;
import visu.handball.moves.model.HandballModel;
import visu.handball.moves.model.MoveEvent;
import visu.handball.moves.model.player.Offender;
import visu.handball.moves.views.Field;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Field_ESTest extends Field_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HandballModel handballModel0 = new HandballModel();
      Graphic graphic0 = new Graphic();
      Graphics2D graphics2D0 = graphic0.createGraphicsShapes((float) 0, (float) 0);
      ColorModel colorModel0 = new ColorModel();
      HandballModel.State handballModel_State0 = HandballModel.State.EDIT;
      handballModel0.setState(handballModel_State0);
      Field field0 = new Field(handballModel0, colorModel0);
      field0.paintComponent(graphics2D0);
      assertFalse(field0.isFocusTraversalPolicyProvider());
  }
}
