/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 23:15:15 GMT 2024
 */

package com.aelitis.azureus.core.dht.router.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.aelitis.azureus.core.dht.DHTLogger;
import com.aelitis.azureus.core.dht.router.DHTRouterContact;
import com.aelitis.azureus.core.dht.router.DHTRouterContactAttachment;
import com.aelitis.azureus.core.dht.router.impl.DHTRouterContactImpl;
import com.aelitis.azureus.core.dht.router.impl.DHTRouterImpl;
import com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DHTRouterNodeImpl_ESTest extends DHTRouterNodeImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment0).getMaxFailForLiveCount();
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl((byte) (-1), 0, (byte) (-30), byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray0, dHTRouterContactAttachment1, true);
      DHTRouterContactAttachment dHTRouterContactAttachment2 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment2).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl1 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment2, true);
      DHTRouterContact dHTRouterContact0 = dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, (byte) (-1));
      assertNotNull(dHTRouterContact0);
      
      dHTRouterNodeImpl0.dead(dHTRouterContactImpl1, true);
      assertTrue(dHTRouterContactImpl1.isReplacement());
      assertFalse(dHTRouterContactImpl1.isBucketEntry());
  }
}
