/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 01:23:07 GMT 2024
 */

package com.liferay.portal.kernel.scheduler;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.scheduler.CronText;
import java.util.Calendar;
import java.util.Locale;
import java.util.TimeZone;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockCalendar;
import org.evosuite.runtime.mock.java.util.MockGregorianCalendar;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CronText_ESTest extends CronText_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Locale locale0 = Locale.CANADA_FRENCH;
      Calendar calendar0 = MockCalendar.getInstance(locale0);
      CronText cronText0 = new CronText(calendar0);
      assertEquals(1, cronText0.getFrequency());
      
      cronText0.setFrequency(7);
      int int0 = cronText0.getFrequency();
      assertEquals(7, int0);
  }
}
