/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 04:21:57 GMT 2024
 */

package com.browsersoft.openhre.hl7.impl.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.browsersoft.openhre.hl7.api.config.HL7Configuration;
import com.browsersoft.openhre.hl7.api.parse.HL7CheckerHandler;
import com.browsersoft.openhre.hl7.api.parse.HL7CheckerState;
import com.browsersoft.openhre.hl7.api.parse.HL7Parser;
import com.browsersoft.openhre.hl7.impl.config.HL7ConfigurationImpl;
import com.browsersoft.openhre.hl7.impl.config.HL7DataTypeImpl;
import com.browsersoft.openhre.hl7.impl.config.HL7FieldImpl;
import com.browsersoft.openhre.hl7.impl.config.HL7SegmentImpl;
import com.browsersoft.openhre.hl7.impl.parser.HL7CheckerImpl;
import com.browsersoft.openhre.hl7.impl.parser.HL7CheckerStateImpl;
import com.browsersoft.openhre.hl7.impl.parser.HL7SAXEventGeneratorImpl;
import java.io.StringReader;
import org.apache.xml.serializer.ToTextStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.xml.sax.helpers.XMLReaderAdapter;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HL7CheckerImpl_ESTest extends HL7CheckerImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HL7CheckerImpl hL7CheckerImpl0 = new HL7CheckerImpl();
      hL7CheckerImpl0.setState((HL7CheckerState) null);
      HL7CheckerState hL7CheckerState0 = hL7CheckerImpl0.getState();
      assertNull(hL7CheckerState0);
  }
}
