/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 01:44:13 GMT 2024
 */

package com.liferay.portal.service.persistence;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.dao.orm.Query;
import com.liferay.portal.kernel.dao.orm.QueryPos;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.persistence.TeamFinderImpl;
import java.util.LinkedHashMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TeamFinderImpl_ESTest extends TeamFinderImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TeamFinderImpl teamFinderImpl0 = new TeamFinderImpl();
      String string0 = teamFinderImpl0.getWhere("com.liferay.portal.service.persistence.TeamFinder.countByG_N_D");
      assertEquals("", string0);
  }
}
