/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 03:08:20 GMT 2024
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.BrowseNode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BrowseNode_ESTest extends BrowseNode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BrowseNode browseNode0 = new BrowseNode();
      browseNode0.setBrowseId("");
      BrowseNode browseNode1 = new BrowseNode();
      browseNode1.addSubNode(browseNode0);
      BrowseNode browseNode2 = browseNode1.getSubNode("");
      assertNotNull(browseNode2);
      assertNotSame(browseNode2, browseNode1);
  }
}
