/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 03:25:07 GMT 2024
 */

package de.beiri22.stringincrementor.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import de.beiri22.stringincrementor.helper.IndexedString;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IndexedString_ESTest extends IndexedString_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IndexedString indexedString0 = new IndexedString("|L$l/`4cKYH");
      char[] charArray0 = new char[3];
      charArray0[0] = '4';
      charArray0[1] = 'c';
      charArray0[2] = 'N';
      int int0 = indexedString0.indexOf(charArray0);
      assertEquals((-1), int0);
  }
}
