/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 00:17:23 GMT 2024
 */

package org.gudy.azureus2.ui.swt.views;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.swt.widgets.Composite;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.gudy.azureus2.core3.download.DownloadManager;
import org.gudy.azureus2.ui.swt.config.generic.GenericIntParameter;
import org.gudy.azureus2.ui.swt.plugins.UISWTView;
import org.gudy.azureus2.ui.swt.pluginsimpl.UISWTViewEventImpl;
import org.gudy.azureus2.ui.swt.pluginsimpl.UISWTViewImpl;
import org.gudy.azureus2.ui.swt.views.TorrentOptionsView;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TorrentOptionsView_ESTest extends TorrentOptionsView_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DownloadManager[] downloadManagerArray0 = new DownloadManager[0];
      TorrentOptionsView torrentOptionsView0 = new TorrentOptionsView(downloadManagerArray0);
      TorrentOptionsView.downloadStateParameterAdapter torrentOptionsView_downloadStateParameterAdapter0 = torrentOptionsView0.new downloadStateParameterAdapter();
      boolean boolean0 = torrentOptionsView_downloadStateParameterAdapter0.getBooleanValue("TorrentOptionsView");
      assertFalse(boolean0);
  }
}
