/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 01:03:40 GMT 2024
 */

package com.liferay.portal.executor;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.executor.PortalExecutorFactoryImpl;
import com.liferay.portal.kernel.concurrent.CallerRunsPolicy;
import com.liferay.portal.kernel.concurrent.ClearThreadLocalThreadPoolHandler;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PortalExecutorFactoryImpl_ESTest extends PortalExecutorFactoryImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PortalExecutorFactoryImpl portalExecutorFactoryImpl0 = new PortalExecutorFactoryImpl();
      portalExecutorFactoryImpl0.setMaxQueueSize(5);
      CallerRunsPolicy callerRunsPolicy0 = new CallerRunsPolicy();
      ClearThreadLocalThreadPoolHandler clearThreadLocalThreadPoolHandler0 = new ClearThreadLocalThreadPoolHandler();
      portalExecutorFactoryImpl0.setThreadPoolHandler(clearThreadLocalThreadPoolHandler0);
      TimeUnit timeUnit0 = TimeUnit.MILLISECONDS;
      portalExecutorFactoryImpl0.setTimeUnit(timeUnit0);
      portalExecutorFactoryImpl0.setRejectedExecutionHandler(callerRunsPolicy0);
      portalExecutorFactoryImpl0.setMaxPoolSize(5);
      portalExecutorFactoryImpl0.afterPropertiesSet();
  }
}
